# @package _global_
# to execute this module run:
# python run.py module=interpolation

defaults:
  - /module@_here_: _base_experiment_config.yaml   # base experiment config with defaults params
  - _self_

module:
  _target_: src.experiment_types.interpolation.NextStepInterpolationExperiment
  monitor: "val/${datamodule.horizon}h_avg/mse"
  stack_window_to_channel_dim: True
  n_autoregressive_train_steps: 0

datamodule:
  horizon: 7   # needs to be > 1
  # multi_horizon: True

model:
  with_time_emb: True