# @package _global_

# example usage:
# `python run.py mode=test_navier_stokes logger.wandb.id=SOME_WANDB_ID`

defaults:
  - test.yaml
  - _self_

datamodule:
  prediction_horizon: 64

logger:
  wandb:
    project: "DYffusion-navier-stokes"  # project in wandb of training runs
    project_test: "DYffusion-Navier-Stokes-TEST"  # overrides logger.wandb.project (allows to use different project for test metrics)
    tags: ["fixed-bc"]


# Checkpoint path to be loaded from wandb cloud (see files tab of run page) or locally (use absolute path)
ckpt_path: "latest_epoch"  # best-val_avg_crps.ckpt"